name = "ENVI"
uuid = "cdc236e2-05f6-455d-8b36-4ce943f8ee7a"
authors = ["John Waczak <john.louis.waczak@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
